#!/usr/bin/python3 
import sys
import getopt

from src.PMMLParser import *
from src.TreeModel import *
from src.HDLGenerator import *

def helpme():
    print("pvmhdmll - a VHDL source code generator for PMML models")
    print("   -h|--help:   print this help screen.")
    print("   -i|--input:  specify the input PMML file to be converted in VHDL.")
    print("   -o|--output: specify the output directory in which VHDL source file will be generated.")
    print("   -p|--print:  enable print.")
    print("You MUST define ALL the mentioned parameters.")

## Command-line parsing
try:
    options, remainder = getopt.getopt(sys.argv[1:], 'i:o:hp', ['input=', 'output=', 'print', 'help'])
except getopt.GetoptError as err:
        print(err)  
        helpme()
        sys.exit(2)

print_tree = False
for opt, arg in options:
    if opt in ('-h', '--help'):
        helpme()
        sys.exit(2)
    elif opt in ('-i', '--input'):
        input_pmml_file = arg
    elif opt in ('-o', '--output'):
        output_dir = arg
    elif opt in ('-p', '--print'):
        print_tree = True

## Here we go...
try:
    print("Input file:      ", input_pmml_file)
    print("Output directury:", output_dir)
    model = PMMLParser(input_pmml_file, print_tree)
    generator = HDLGenerator(model.get_features(), model.get_classes(), model.get_trees())
    generator.generate(output_dir)
       

except NameError as err:
    print (err.message)
    helpme()
    sys.exit(2)








